version: '3.1'
services:
  backup_utilities:
    image: 'automated_backup_utilities:latest'
    restart: always      
    tty: true
    stdin_open: true
    env_file:
      .env
    command: python3 app.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
