version: '3.1'
services:
  backup_utilities:
    image: 'automated_backup_utilities:latest'
    restart: always      
    tty: true
    stdin_open: true
    env_file:
      .env
    environment:
      CONFIG_PATH: /config.yaml
    command: python3 app.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_PATH:/config.yaml
      # TODO: Find a better way to handle this volume sharing
      - /tmp/:/tmp/

